services:
  kiro-go:
    build: .
    container_name: kiro-go
    ports:
      - "18080:8080"
      - "3128:3128"
      - "3129:3129"
      - "56121:56121"
    volumes:
      - /home/ruanling/.kirogo:/app/data
    env_file:
      - /home/ruanling/.kirogo/.env
    environment:
      CONFIG_PATH: /app/data/config.json
      LOG_LEVEL: debug
      KIRO_SSO_CALLBACK_BIND: 0.0.0.0
      ANTIGRAVITY_CALLBACK_BIND: 0.0.0.0
      XAI_CALLBACK_BIND: 0.0.0.0
    restart: unless-stopped
